# Generated by Django 4.0.4 on 2022-11-12 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ttile',
            new_name='title',
        ),
    ]
